### ISSUE TITLE
NotADirectoryError: [Errno 20] Not a directory: 'sample_imgs/.DS_Store'

### ISSUE THREAD

**Issue by wengjincheng** [benjiebob/StanfordExtra#8]
I can't find the .DS_Store file

**Comment by OllieBoyne** [comment]
There shouldn't be a `.DS_Store` file in the `sample_imgs` directory. If you've downloaded the folder on a Mac, this file might have appeared. Please delete it and the problem should be resolved.

**Comment by benjiebob** [comment]
Closing for now :)
